channels:
- conda-forge
dependencies:
- python=3.11.7
- pip<=23.3.1
- pip:
  - mlflow==2.12.2
  - cffi==1.16.0
  - click==8.1.7
  - cloudpickle==2.2.1
  - colorama==0.4.6
  - cytoolz==0.12.2
  - defusedxml==0.7.1
  - distributed==2023.11.0
  - imbalanced-learn==0.11.0
  - importlib-metadata==7.0.1
  - jinja2==3.1.3
  - lightgbm==4.3.0
  - lz4==4.3.2
  - matplotlib==3.8.0
  - numpy==1.26.4
  - packaging==23.1
  - pandas==2.1.4
  - pathlib==1.0.1
  - pyarrow==14.0.2
  - python-snappy==0.6.1
  - pyyaml==6.0.1
  - scikit-learn==1.2.2
  - scipy==1.11.4
  - zstandard==0.19.0
name: mlflow-env
